# Generated by Django 4.1 on 2022-08-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
