# Generated by Django 4.0 on 2022-10-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barra',
        ),
    ]
