# Generated by Django 4.1 on 2022-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rif',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
