# Generated by Django 4.1 on 2022-08-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_cliente_rif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rif',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
