# Generated by Django 4.1 on 2022-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_cliente_rif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rif',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
