# Generated by Django 4.1 on 2022-08-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_facturaenc_facturadet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rif',
            field=models.CharField(max_length=8),
        ),
    ]
