# Generated by Django 4.1 on 2022-08-18 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_alter_cliente_rif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturadet',
            old_name='descuento',
            new_name='gastos_adicionales',
        ),
        migrations.RenameField(
            model_name='facturaenc',
            old_name='descuento',
            new_name='gastos_adicionales',
        ),
    ]
