# Generated by Django 4.1 on 2022-08-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_rename_descuento_facturadet_gastos_adicionales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturadet',
            old_name='gastos_adicionales',
            new_name='descuento',
        ),
        migrations.RenameField(
            model_name='facturaenc',
            old_name='gastos_adicionales',
            new_name='descuento',
        ),
    ]
