# Generated by Django 4.1 on 2022-08-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_rename_gastos_adicionales_facturadet_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadet',
            name='estado',
            field=models.CharField(max_length=3),
        ),
    ]
