# Generated by Django 4.1 on 2022-08-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_alter_facturadet_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadet',
            name='estado',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
