# Generated by Django 4.1 on 2022-08-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_alter_facturadet_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadet',
            name='user_borra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
