# Generated by Django 4.1 on 2022-08-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_alter_facturadet_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='tipo_pago',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
