# Generated by Django 4.1 on 2022-08-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_facturaenc_pagado_facturaenc_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaenc',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
