# Generated by Django 4.1 on 2022-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_facturaenc_user_cobra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombres',
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(default='jesus delgado', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
