# Generated by Django 4.0 on 2022-10-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_rename_celular_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='monto',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
