# Generated by Django 4.0 on 2022-12-08 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasdet',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='comprasdet',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
