# Generated by Django 4.1 on 2022-08-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default='hola', max_length=20),
            preserve_default=False,
        ),
    ]
