# Generated by Django 4.0 on 2022-10-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
