# Generated by Django 4.1 on 2022-08-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_comprasenc_pagado_comprasenc_tipo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
