# Generated by Django 4.0 on 2022-10-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasenc',
            name='monto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
