# Generated by Django 4.0 on 2022-10-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0007_comprasenc_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='monto',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
