# Generated by Django 4.0 on 2022-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0008_alter_comprasenc_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasenc',
            name='descripcion_gastos_adicionales',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
