# Generated by Django 4.0 on 2022-10-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0009_comprasenc_descripcion_gastos_adicionales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasenc',
            name='descripcion_gastos_adicionales',
        ),
        migrations.RemoveField(
            model_name='comprasenc',
            name='gastos_adicionales',
        ),
    ]
