# Generated by Django 4.0 on 2022-10-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0010_remove_comprasenc_descripcion_gastos_adicionales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasdet',
            name='gastos_adicionales',
        ),
    ]
