# Generated by Django 4.0 on 2022-10-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gastos',
        ),
    ]
